
WARNING : mc16_13TeV.395033.MGPy8EG_A14N23LO_SM_N2C1p_255_250_2L2MET75_MadSpin.recon.AOD.e7035_a875_r10724 is unmerged AOD dataset which is not distributed. Please use mc*.merge.AOD.* instead

INFO : Need to generate a grid proxy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/PandaClient/1.4.36/lib/python2.7/site-packages/pandatools/PrunScript.py", line 754, in <module>
    listProjects = Client.getCachePrefixes(options.verbose)
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/PandaClient/1.4.36/lib/python2.7/site-packages/pandatools/Client.py", line 718, in getCachePrefixes
    status,output = curl.get(url,{})
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/PandaClient/1.4.36/lib/python2.7/site-packages/pandatools/Client.py", line 161, in get
    s,o = commands_get_status_output(com)
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/PandaClient/1.4.36/lib/python2.7/site-packages/pandatools/MiscUtils.py", line 129, in commands_get_status_output
    data, unused_err = p.communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
